import java.math.MathContext
import java.math.RoundingMode
def d = 123.456G
println d.round(new MathContext(4))
println d.round(new MathContext(2))
println 999.5G.round(new MathContext(3))
println d.round(new MathContext(2, RoundingMode.DOWN))
println 1.0G.divide(3G, new MathContext(5))
println 10.0G.divide(4G, MathContext.DECIMAL32)
println 1.5G.add(2.25G, new MathContext(2))
println 2.0G.sqrt(new MathContext(10))
println 4.0G.sqrt(new MathContext(10))
println 16.00G.sqrt(new MathContext(10))
println new MathContext(7)
println MathContext.DECIMAL64
println MathContext.DECIMAL128.getPrecision()
println new MathContext(3, RoundingMode.FLOOR).getRoundingMode()
println d.setScale(1, RoundingMode.HALF_UP)
println d.setScale(0, RoundingMode.CEILING)
println d.setScale(2, BigDecimal.ROUND_DOWN)
println BigDecimal.ROUND_HALF_UP
println RoundingMode.valueOf('UP')
println RoundingMode.values().size()
println 12.5G.movePointLeft(3)
println 12.5G.movePointRight(3)
println 5.0G.divideToIntegralValue(2G)
println 1E+3G.toEngineeringString()
println 12345.678G.toEngineeringString()
println 1.5G.max(2.5G)
println((-1.5G).signum())
println 1.5G.scaleByPowerOfTen(3)
println 15G.gcd(10G)
println((-5G).bitLength())
println 255G.bitLength()
println 255G.bitCount()
println 5G.testBit(2)
println 5G.setBit(1)
println 5G.clearBit(0)
println 5G.flipBit(3)
println 97G.isProbablePrime(10)
println 91G.isProbablePrime(10)
println 100G.nextProbablePrime()
println 4G.modPow(13G, 497G)
println 3G.modInverse(7G)
println 100G.sqrt()
println new BigInteger('ff', 16)
println new BigInteger('-1010', 2)
println BigInteger.valueOf(Long.MAX_VALUE) + 1
println BigInteger.valueOf(7).pow(30)
println BigDecimal.valueOf(25, 1)
println BigDecimal.valueOf(2.5)
println 7G.max(9G)
println 7G.signum()
try { 100G.setScale(2) } catch (e) { println e.getClass().getSimpleName() }
try { 100G.precision() } catch (e) { println e.getClass().getSimpleName() }
try { 1.5G.intValueExact() } catch (e) { println e.getClass().getSimpleName() }
try { 5G.modInverse(0G) } catch (e) { println e.getClass().getSimpleName() }
try { 2G.modInverse(4G) } catch (e) { println e.message }
println 1.5G.byteValue()
println 300G.byteValue()
println 70000.7G.shortValue()
println 3.99.byteValue()
println (+d)
println (+3)
