def t = { String label, Closure c -> try { println "$label = ${c()}" } catch (e) { println "$label ! ${e.getClass().getName()}" } }
def src = [3, 1, 2]
def im = src.asImmutable()
src << 9
t('imm list', { im })
t('imm add', { im << 4 })
t('imm set', { im[0] = 1 })
t('imm sort', { im.sort() })
t('imm sorted copy', { im.sort(false) })
t('imm clear', { im.clear() })
t('imm remove', { im.remove(0) })
t('imm class', { im.getClass().getName() })
def view = Collections.unmodifiableList(src)
t('unmod add', { view.add(1) })
t('unmod class', { view.getClass().getName() })
t('unmod read', { view.size() })
def lo = List.of(1, 2, 3)
t('List.of', { lo })
t('List.of add', { lo.add(4) })
t('List.of class', { lo.getClass().getName() })
t('List.of small', { List.of(1).getClass().getName() })
t('List.of null', { List.of(1, null) })
t('List.of contains', { lo.contains(2) })
def al = Arrays.asList(1, 2, 3)
t('asList', { al })
t('asList add', { al.add(4) })
t('asList remove', { al.remove(0) })
al[0] = 99
t('asList set', { al })
t('asList class', { al.getClass().getName() })
def ms = [a: 1].asImmutable()
t('imm map', { ms })
t('imm map put', { ms.put('b', 2) })
t('imm map assign', { ms.b = 2 })
t('imm map class', { ms.getClass().getName() })
t('Map.of', { Map.of('k', 1).get('k') })
t('Map.of put', { Map.of('k', 1).put('j', 2) })
t('Map.of dup', { Map.of('k', 1, 'k', 2) })
def ss = ([1, 2] as Set).asImmutable()
t('imm set', { ss })
t('imm set add', { ss.add(3) })
t('imm set class', { ss.getClass().getName() })
t('Set.of dup', { Set.of(1, 1) })
t('empty list', { Collections.emptyList().add(1) })
t('empty class', { Collections.emptyList().getClass().getName() })
t('singleton list', { Collections.singletonList(1).add(2) })
t('nCopies', { Collections.nCopies(3, 'x') })
t('nCopies add', { Collections.nCopies(3, 'x').add('y') })
t('unmod map', { Collections.unmodifiableMap([a: 1]).put('b', 1) })
t('unmod set', { Collections.unmodifiableSet([1] as Set).add(2) })
t('copy still mutable', { def c = new ArrayList(im); c << 5; c })
